# -*- mode: ruby; coding: utf-8 -*-
require 'rubygems'
require 'bundler'
require 'cucumber/rake/task'
require 'rake/hooks'

Cucumber::Rake::Task.new(:features) do |t|
  t.cucumber_opts = "features --format pretty"
end

before :features do
  system "rackup --port 4567 --daemon"
end

after :features do
  system "kill `cat rack.pid`"
end

