# Generated by cucumber-sinatra. (2014-04-19 10:21:54 +0900)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/parking_lot_calculator.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = ParkingLotCalculator

class ParkingLotCalculatorWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ParkingLotCalculatorWorld.new
end
